### ISSUE TITLE
[Batch] Prep for handover

### ISSUE THREAD

**Issue by ipc103** [github-community-projects/org-metrics-dashboard#101]
Tracking a list of todos/items for being able to hand ownership of this project. 

- [x] #102 
- [x] #103
- [ ] #104
- [x] #44 
- [x] #98 
- [x] Discuss additional strategies for snapshot data (see note below)
- [ ] Incorporate #38 to be able to switch between light and dark modes

In addition to the current snapshots, we should discuss possibilities for getting more robust snapshot data. One option is to allow writing data to an (optional) database on a more frequent cron, then generate `data.json` files at build/deploy time. This would provide a more robust storage system, but would require more maintenance for the individual project owner as we move forward.

**Comment by ajhenry** [comment]
Marking this as complete, we can follow up with additional items later
