### ISSUE TITLE
The PAT scope "read:repo" vs "public_repo" 

### ISSUE THREAD

**Issue by lukech** [github-community-projects/org-metrics-dashboard#167]
In the "Actions" section of the readme, "read:repo" is listed as one scope that needs to be selected when creating a personal access token (PAT). When attempting to create a PAT (the classic) I found that "read:repo" was not an option ("read:repo_hook" is the closest one that I ticked). With this PAT/secret my [Github actions run](https://github.com/wiredtiger/org-metrics-dashboard/actions/runs/10695783598/job/29650084978) (the "build" job) failed with the below signature, indicating the "public_repo" scope is required. 
```
GraphqlResponseError: Request failed due to following response errors:
 - Your token has not been granted the required scopes to execute this query. The 'totalCount' field requires one of the following scopes: ['public_repo'], but your token has only been granted the: ['read:org', 'read:project', 'read:repo_hook'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
``` 
After recreating a new PAT with the "public_repo" scope (besides "read:org" and "read:project") the build step passed. 

Could someone please confirm that the non-existent "read:repo" PAT scope should be replaced by the "public_repo" scope in the readme? Thanks.

**Comment by bmuenzenmeyer** [comment]
> Could someone please confirm that the non-existent "read:repo" PAT scope should be replaced by the "public_repo" scope in the readme? Thanks.

Not with the GH OSPO, but my company's, and I can confirm that `public_repo` worked for me today

**Comment by lukech** [comment]
Thanks for confirming @bmuenzenmeyer. I'd hope one of the maintainers could advise if the readme needs an update by including the "public_repo" scope (and possibly removing the "read:repo" scope).

**Comment by ChrisCarini** [comment]
Also confirmed. Gave an approval to https://github.com/github-community-projects/org-metrics-dashboard/pull/168#pullrequestreview-2306340465 - hopefully one of the maintainers of this repo takes a look and accepts the PR.
