### ISSUE TITLE
Metric: Repositories

### ISSUE THREAD

**Issue by liliana3186** [github-community-projects/org-metrics-dashboard#46]
This issue tracks the completeness of the metric.

Business Question: How many Repositories the Organization has?

How to calculate metrics [here](https://docs.google.com/spreadsheets/d/1wfG56fRevfbEIOgDoR3_uFyaq9cd30HxrwDcjbzi3uo/edit#gid=0)

### Tasks
- [ ] Create/update backend to fetch Issues by Status
- [ ] Visualize it in

**Comment by ipc103** [comment]
This is now visible on the main table



![Image](https://github.com/sbv-world-health-org-metrics/sbv-world-health-org-metrics/assets/6826778/799f765a-310d-44a5-ae4e-647736a7152e)
